version: "3"
services:
  ports:
    build:
      context: .
    environment:
      - DB_HOST=mongodb://mongo:27017
      - DB_USER
      - DB_PASSWORD
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password